---
- name: Create Matchbox group
  group:
    name: matchbox
    state: present
  become: yes

- name: Create Matchbox user
  user:
    name: matchbox
    group: matchbox
    state: present
  become: yes

