---
- name: Download CoreOS with Matchbox scripts
  shell: "./get-coreos stable {{ matchbox_coreos_version }} ."
  args:
    chdir: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts"
    creates: "./coreos/{{ matchbox_coreos_version }}/"
  register: matchbox_coreos_download

- name: Move to assets folder
  command: "cp -r {{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/coreos/ {{ matchbox_assets_dir }}/"
  args:
    creates: "{{ matchbox_assets_dir }}/coreos"
  become: yes

- name: Set correct permissions on assets folder
  file:
    path: "{{ matchbox_assets_dir }}/coreos/"
    state: directory
    owner: matchbox
    group: matchbox
    recurse: yes
  become: yes

- block:

  - name: Delete previous CoreOS versions
    find:
      paths:
        - "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/coreos/"
        - "{{ matchbox_assets_dir }}/coreos/"
      file_type: directory
    register: matchbox_existing

  - name: Delete unwanted files
    file:
      path: "{{ item.path }}"
      state: absent
    when: "{{ item.path|basename }} != {{ matchbox_coreos_version }}"
    with_items: "{{ matchbox_existing.files | default([]) }}"

  when: matchbox_coreos_download.changed
