---
- name: Download CoreOS with Matchbox scripts
  shell: "./get-coreos stable {{ matchbox_coreos_version }} ."
  args:
    chdir: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts"

- name: Move to assets folder
  copy:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}/coreos"
    dest: /var/lib/matchbox/assets