---
- name: Create Matchbox group
  group:
    name: matchbox
    state: present
  become: yes

- name: Create Matchbox user
  user:
    name: matchbox
    group: matchbox
    state: present
  become: yes

- name: Setup assets directory
  file:
    path: "{ matchbox_assets_dir }}"
    owner: matchbox
    group: matchbox
    state: directory
  become: yes
