---
- name: Download CoreOS with Matchbox scripts
  shell: "./get-coreos stable {{ matchbox_coreos_version }} ."
  args:
    chdir: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts"
    creates: "./coreos/{{ matchbox_coreos_version }}/"

- name: Move to assets folder
  command: "cp -r {{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/coreos/{{ matchbox_coreos_version }} /var/lib/matchbox/assets/coreos/"
