---
- name: Download CoreOS with Matchbox scripts
  shell: "./get-coreos stable {{ item }} {{ matchbox_assets_dir }}"
  args:
    chdir: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts"
    creates: "{{ matchbox_assets_dir }}/coreos/{{ item }}/"
  with_items: matchbox_coreos_version
  register: matchbox_coreos_download

- name: Set correct permissions on assets folder
  file:
    path: "{{ matchbox_assets_dir }}/coreos/"
    state: directory
    owner: matchbox
    group: matchbox
    recurse: yes
  become: yes

- block:

  - name: Delete previous CoreOS versions
    find:
      paths: "{{ matchbox_assets_dir }}/coreos/"
      file_type: directory
    become: yes
    register: matchbox_existing

  - name: Delete unwanted files
    file:
      path: "{{ item.path }}"
      state: absent
    when: item.path|basename not in matchbox_coreos_version
    with_items: "{{ matchbox_existing.files | default([]) }}"
    become: yes

  when: matchbox_coreos_download.changed
