---
- name: Ensure download and install dir exist
  file:
    path: "{{ matchbox_download_dir }}"
    state: directory

- name: Download Matchbox and PGP file
  get_url:
    url: "{{ item }}"
    dest: "{{ matchbox_download_dir }}"
  with_items:
    - "{{ matchbox_url }}"
    - "{{ matchbox_url + '.asc' }}"

- name: Download CoreOS App Signing key (https://coreos.com/security/app-signing-key/)
  shell: gpg --keyserver pgp.mit.edu --recv-key 18AD5014C99EF7E3BA5F6CE950BDD3E0FC8A365E
  changed_when: false

- name: Verify Matchbox
  shell: "gpg --verify matchbox-v{{ matchbox_version }}-linux-amd64.tar.gz.asc matchbox-v{{ matchbox_version }}-linux-amd64.tar.gz"
  args:
    chdir: "{{ matchbox_download_dir }}"
  changed_when: false

- name: Unpack release tarball
  unarchive:
    src: "{{ matchbox_download_dir }}/matchbox-v{{ matchbox_version }}-linux-amd64.tar.gz"
    dest: "{{ matchbox_download_dir }}"
    remote_src: yes

- name: Symlink Matchbox executable
  file:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}/matchbox"
    dest: "{{ matchbox_executable_dir }}/matchbox"
    state: link
  become: yes

- name: Copy Matchbox systemd file
  copy:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}/contrib/systemd/matchbox.service"
    dest: /etc/systemd/system/matchbox.service
    remote_src: yes
  become: yes

- name: Create systemd override directory
  file:
    path: /etc/systemd/system/matchbox.service.d
    state: directory
  become: yes

- name: Create systemd override.conf
  template:
    src: templates/systemd-override.conf.j2
    dest: /etc/systemd/system/matchbox.service.d/override.conf
  become: yes

- name: Create assets folder
  file:
    path: "{ matchbox_assets_dir }}"
    state: directory
    owner: matchbox
    group: matchbox
  become: yes

- name: Enable Matchbox and reload daemon
  systemd:
    name: matchbox
    enabled: yes
    daemon_reload: yes
  become: yes
  notify: matchbox restart