---
- import_tasks: load-variables.yml

#- include: setup-epel.yml

#- include: setup-prerequisite.yml

- import_tasks: install-matchbox.yml

- import_tasks: setup-grpc.yml
  when: matchbox_enable_grpc

- import_tasks: add-coreos.yml
  when: matchbox_enable_coreos_pxe