---
- name: Generate TLS certificates
  shell: ./cert-gen
  args:
    chdir: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/tls"
    creates: ca.crt
  environment:
    SAN: "DNS.1:{{ matchbox_hostname }},IP.1:{{ ansible_default_ipv4.address }}"
  when: matchbox_selfsigned_certs
  notify: matchbox restart

- name: Create /etc/matchbox
  file:
    dest: /etc/matchbox
    state: directory
  become: yes

- name: Copy TLS credentials to /etc/matchbox
  copy:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/tls/{{ item }}"
    dest: /etc/matchbox
    remote_src: yes
  with_items:
    - ca.crt
    - server.crt
    - server.key
  become: yes

- name: Create matchbox_client_cert_dir
  file:
    dest: "{{ matchbox_client_cert_dir }}"
    state: directory

- name: Copy client certs to to client_cert_dir
  copy:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/tls/{{ item }}"
    dest: "{{ matchbox_client_cert_dir }}"
    remote_src: yes
  with_items:
    - ca.crt
    - client.crt
    - client.key
