---
- name: Symlink Matchbox systemd file
  file:
    src: "{{ matchbox_install_location }}/contrib/systemd/matchbox.service"
    dest: /etc/systemd/system/matchbox.service

- name:
  blockinfile:
    dest: /etc/systemd/system/matchbox.service.d/override.conf
    block: "{{ matchbox_systemd_override }}"
    marker: "<!-- {mark} ANSIBLE MANAGED CONFIG -->"
    insertafter: EOF

- name: Set ExexStart in systemd override.conf
  lineinfile:
    dest: "{{ matchbox_install_location }}/contrib/systemd/matchbox.service"
    regexp: "^ExecStart="
    line: "ExecStart={{ matchbox_executable_location }}"