---
- name: Set Rpc adress in systemd override.conf
  lineinfile:
    dest: /etc/systemd/system/matchbox.service.d/override.conf
    regexp: '^Environment="MATCHBOX_RPC_ADDRESS='
    line: 'Environment="MATCHBOX_RPC_ADDRESS=0.0.0.0:8081"'
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  notify: matchbox restart
  become: yes

- name: Generate TLS certificates
  shell: ./cert-gen
  args:
    chdir: "{{ matchbox_download_dir }}/{{ matchbox_src }}/scripts/tls"
    creates:
      - ca.crt
      - server.crt
      - server.key
      - client.crt
      - client.key
  environment:
    SAN: "DNS.1:{{ matchbox_hostname }},IP.1:{{ ansible_default_ipv4.address }}"
  when: matchbox_selfsigned_certs

- name: Create /etc/matchbox and client_cert_dir
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - /etc/matchbox
    - "{{ matchbox_client_cert_dir }}"
  become: yes

- name: Move TLS credentials to /etc/matchbox
  copy:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}scripts/tls/{{ item }}"
    dest: /etc/matchbox
  with_items:
    - ca.crt
    - server.crt
    - server.key
  become: yes

- name: Move client certs to to client_cert_dir
  copy:
    src: "{{ matchbox_download_dir }}/{{ matchbox_src }}scripts/tls/{{ item }}"
    dest: "{{ matchbox_client_cert_dir }}"
  with_items:
    - ca.crt
    - client.crt
    - client.key
